#include "nostromo/applet/ac_properties.h"
#include "nostromo/applet/applet.h"
#include "nostromo/clock.h"
#include "nostromo/dsp.h"
#include "nostromo/midi.h"
#include "nostromo/math.h"
#include "nostromo/fixed.h"
#include "nostromo/generators/flip-flop-pattern.h"
#include "nostromo/oscillators/oscillator.h"
#include "nostromo/oscillators/phasor.h"
#include "nostromo/oscillators/shapes.h"
#include "nostromo/oscillators/shark-tooth.h"
#include "nostromo/perlin.h"
#include "nostromo/properties/property.h"
#include "nostromo/properties/string_conversion.h"
#include "nostromo/random.h"

#define K(a) true
